### ISSUE TITLE
if polar is selected the IRamanWorkChain should take that into account to run the average workchain

### ISSUE THREAD

**Issue by mikibonacci** [mikibonacci/aiidalab-qe-vibroscopy#18]
As pointed out by @AndresOrtegaGuerrero .

**Comment by AndresOrtegaGuerrero** [comment]
@mikibonacci I think this might not be needed (we need to double check), since the widget of visualisation can compute already the power and.or the crystal spectrum. We can double check with Lorenzo , but i think with the widget the user can actually decide which spectrum they want.

**Comment by mikibonacci** [comment]
Lorenzo told me that the average computed in the average workchain is different: it integrates on q. instead, the direct function to compute powder just an average on the irreducible modes. However, I will open another issue on this, as in the new aiida-vibroscopy release there will be a simple function (not aiida) to do also this.

**Comment by AndresOrtegaGuerrero** [comment]
i checked his workchain, https://github.com/bastonero/aiida-vibroscopy/blob/main/src/aiida_vibroscopy/workflows/spectra/intensities_average.py , what is the difference ?

**Comment by mikibonacci** [comment]
I checked more deeply, and actually I think nothing, apart the fact that to have the q integral we just have to define the quadrature order. So if we define it in the app, should work.

**Comment by AndresOrtegaGuerrero** [comment]
ahh ok !  then we have to modify the workchain indeed
