### ISSUE TITLE
Display which workchain property is run

### ISSUE THREAD

**Issue by AndresOrtegaGuerrero** [mikibonacci/aiidalab-qe-vibroscopy#22]
When selecting the workchain in aiidalab-qe , instead of displaying vibronic , it should display the property, like iraman, phonon bands, phonons pdos, dielectric constant ....

**Comment by AndresOrtegaGuerrero** [comment]
<img width="1134" alt="Screenshot 2023-12-02 at 10 25 44" src="https://github.com/mikibonacci/aiidalab-qe-vibroscopy/assets/34098967/c82b3f15-88c0-4c83-9737-f6e3cf8a3282">

Like one thing we need to bring to the discussion of the aiidalab-qe app , is a search engine, this part once you have different calculations is quite difficult

**Comment by mikibonacci** [comment]
Hi @AndresOrtegaGuerrero, I think we should then split into two workchains: vibronic, in case of HarmonicWorkChain and PhononWorkchain, and IRamanWorkChain. The at this point we should also make runnable directly the DielectricWorkchain. 

However, this goes back to the previous implementation. But I think it is the only way to show explicitely what you are running. 

Maybe there is the possibility to modify the worktree directly, to easily inspect the true workchain. I am thinking about this as we were discussing about changing its logic/view

**Comment by mikibonacci** [comment]
closing this issue, now we can put tags and labels attached to the run.
