### ISSUE TITLE
select live the frequency and temperature for raman and IR spectra plots

### ISSUE THREAD

**Issue by mikibonacci** [mikibonacci/aiidalab-qe-vibroscopy#4]

**Comment by AndresOrtegaGuerrero** [comment]
i think with #19 you are hidden the option of frequency and temperature

**Comment by AndresOrtegaGuerrero** [comment]
ahh ok, then we can close it, since we are already doing this. https://aiida-vibroscopy.readthedocs.io/en/latest/howto/postprocess.html#how-to-get-powder-spectra 

The only thing might be pending is to consider only pol_incoming=incoming for IR and ignore outcoming

**Comment by mikibonacci** [comment]
right... I will do it
