### ISSUE TITLE
the plugin should display the phonopy code

### ISSUE THREAD

**Issue by AndresOrtegaGuerrero** [mikibonacci/aiidalab-qe-vibroscopy#6]
When installing the plugin in qe-app it should display a widget in the computational resources step for phonopy

**Comment by mikibonacci** [comment]
Hi @AndresOrtegaGuerrero, this is indeed right. However, for what I know, phonopy can run only in serial, meaning that I always set 1 core for the simulation. 
For parallel execution we should consider phono3py (https://sourceforge.net/p/phonopy/mailman/message/34447034/).

This is why I hardcoded the resources, but I agree with you.

**Comment by AndresOrtegaGuerrero** [comment]
i see, but the code should be with the same computer within aiida right? like pw@daint and phonopy@daint right ?

**Comment by AndresOrtegaGuerrero** [comment]
so the resources are hardcoded to use the localhost ?  , because we could also use something like `from aiidalab_widgets_base import (
    ComputationalResourcesWidget,
)

PhonopyCode = ComputationalResourcesWidget(
            description="phonopy:",
            default_calc_job_plugin="phonopy.phonopy",
        )

class Outline(OutlinePanel):
    title = "Vibrational properties"
    #description = "IR and Raman spectra; you may also select phononic and dielectric properties"



property ={
"outline": Outline,
"code": {"phonopy": PhonopyCode},
"setting": Setting,
"workchain": workchain_and_builder,
"result": Result,
}`

**Comment by mikibonacci** [comment]
The resources are hardcoded to use localhost and only one core. 
actually, I already added the phonopy code, but I didn't push. Did right now!

**Comment by mikibonacci** [comment]
Should be the same code that you wrote in the comment above
