### ISSUE TITLE
Overrides is not updated

### ISSUE THREAD

**Issue by AndresOrtegaGuerrero** [mikibonacci/aiidalab-qe-vibroscopy#61]
the advanced configuration settings arent used in the workchains.

**Comment by AndresOrtegaGuerrero** [comment]
@mikibonacci This one is puzzling me , it is not using Smearing width  or others. i tested for the Harmonic and the Iraman... and it doesnt work

**Comment by mikibonacci** [comment]
mmm, interesting in a bad way... let me check. Thanks for bringing up this!

**Comment by mikibonacci** [comment]
I will see if I can fix this in [this PR](https://github.com/mikibonacci/aiidalab-qe-vibroscopy/pull/62), which I would like to merge tomorrow if possible

**Comment by mikibonacci** [comment]
Done [here](https://github.com/mikibonacci/aiidalab-qe-vibroscopy/pull/62/commits/88591c1f0c100391ba68413646d8344fd689eace), in the PR commit. However, if you don't have time to review and you need the bugfix, I can do a PR only for the single commit. I think the PR should be easy as I merged main into that before submitting the pr.

**Comment by AndresOrtegaGuerrero** [comment]
> Done [here](https://github.com/mikibonacci/aiidalab-qe-vibroscopy/pull/62/commits/88591c1f0c100391ba68413646d8344fd689eace), in the PR commit. However, if you don't have time to review and you need the bugfix, I can do a PR only for the single commit. I think the PR should be easy as I merged main into that before submitting the pr.

How this commit fix the issue ?

**Comment by mikibonacci** [comment]
The full pw override was put to be equal to a dictionary containing metadata stuff, but it was wrong as the metadata stuff should be in the correct "metadata" key of the pw dictionary. Doing in that way, the full pw override was overridden itself, so we lose the info on the advanced config. 
Should be clear by checking the commit 

Check the commit before the last one, should be enough clear?

**Comment by AndresOrtegaGuerrero** [comment]
I see it now! , thank you ! that was on me!
