### ISSUE TITLE
reducing mesh for pdos and thermo for cheaper simulations

### ISSUE THREAD

**Issue by mikibonacci** [mikibonacci/aiidalab-qe-vibroscopy#67]
Hi @AndresOrtegaGuerrero , I was thinking to reduce the mesh sampling in the PhonopyCalculations for pdos and thermo, as I tried in my laptop and was not possible to run these steps. I am thinking that maybe we can reduce it and/or put some input parameter in the settings. In the end, Probably the sampling is already a lot, and we can safely reduce it. 

I will do some more test on this, but great if you already have some experience in this.

**Comment by mikibonacci** [comment]
now we have these settings:

```bash
MESH=1000
TPROP=.True.
WRITE_MESH=.False.
HDF5=.True.
```

**Comment by AndresOrtegaGuerrero** [comment]
so usually i am running phonopy in the cluster as well, not locally , I dont know what could be an adequate value , but i guess we can do some tests and reduce it ?

**Comment by AndresOrtegaGuerrero** [comment]
btw, is this for pdos ? because in the workchain we use 300
