### ISSUE TITLE
INS fails with 1D system

### ISSUE THREAD

**Issue by AndresOrtegaGuerrero** [mikibonacci/aiidalab-qe-vibroscopy#69]
![Screenshot 2024-06-14 at 16 15 11](https://github.com/mikibonacci/aiidalab-qe-vibroscopy/assets/34098967/ea9ca48e-ff71-4b8a-81ac-04c9e3ead3f6)

**Comment by mikibonacci** [comment]
the problem is that seekpath is used in euphonic. We can just use the code in the workchain used in the bands to provide the path  for low-D systems.
