### ISSUE TITLE
AiiDA Vibroscopy should be install as --user 

### ISSUE THREAD

**Issue by AndresOrtegaGuerrero** [mikibonacci/aiidalab-qe-vibroscopy#80]
If there is a restart in the server , aiida_vibroscopy and other libraries arent found

**Comment by AndresOrtegaGuerrero** [comment]
this also applies to the other dependencies , they should be installed as --user. 
We might need something like `pip install --user -r requirements.txt` , that is enforced in aiidalab_qe , to recover from a restart in the server

**Comment by mikibonacci** [comment]
In principle something can be done here: https://github.com/aiidalab/aiidalab-qe/blob/main/plugin_list.ipynb adding the -r requirements.txt in the command. but let's discuss more, and understand if this will work also for other plugins which will not have the txt file.
